-- MySQL Script generated by MySQL Workbench
-- Sat May  9 22:58:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DOM-T
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DOM-T
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DOM-T` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `DOM-T` ;

-- -----------------------------------------------------
-- Table `DOM-T`.`almacenComputadoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`almacenComputadoras` (
  `idcomputadoras` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `direccion` TEXT NOT NULL,
  PRIMARY KEY (`idcomputadoras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`almacenRopa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`almacenRopa` (
  `idalmacenRopa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` TEXT NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idalmacenRopa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`restaurate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`restaurate` (
  `idrestaurate` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `direccion` TEXT NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrestaurate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`almacenCopiadoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`almacenCopiadoras` (
  `idcopiadoras` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` TEXT NOT NULL,
  PRIMARY KEY (`idcopiadoras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `telefonol` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`ferreteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`ferreteria` (
  `idferreteria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `direccion` TEXT NOT NULL,
  PRIMARY KEY (`idferreteria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`electrodomesticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`electrodomesticos` (
  `idelectrodomesticos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `direccion` TEXT NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idelectrodomesticos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `telefonol` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `computadoras_idcomputadoras` INT NOT NULL,
  `almacenRopa_idalmacenRopa` INT NOT NULL,
  `restaurate_idrestaurate` INT NOT NULL,
  `almacenCopiadoras_idcopiadoras` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  `ferreteria_idferreteria` INT NOT NULL,
  `electrodomesticos_idelectrodomesticos` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_computadoras1_idx` (`computadoras_idcomputadoras` ASC) VISIBLE,
  INDEX `fk_cliente_almacenRopa1_idx` (`almacenRopa_idalmacenRopa` ASC) VISIBLE,
  INDEX `fk_cliente_restaurate1_idx` (`restaurate_idrestaurate` ASC) VISIBLE,
  INDEX `fk_cliente_almacenCopiadoras1_idx` (`almacenCopiadoras_idcopiadoras` ASC) VISIBLE,
  INDEX `fk_cliente_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  INDEX `fk_cliente_ferreteria1_idx` (`ferreteria_idferreteria` ASC) VISIBLE,
  INDEX `fk_cliente_electrodomesticos1_idx` (`electrodomesticos_idelectrodomesticos` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_computadoras1`
    FOREIGN KEY (`computadoras_idcomputadoras`)
    REFERENCES `DOM-T`.`almacenComputadoras` (`idcomputadoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_almacenRopa1`
    FOREIGN KEY (`almacenRopa_idalmacenRopa`)
    REFERENCES `DOM-T`.`almacenRopa` (`idalmacenRopa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_restaurate1`
    FOREIGN KEY (`restaurate_idrestaurate`)
    REFERENCES `DOM-T`.`restaurate` (`idrestaurate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_almacenCopiadoras1`
    FOREIGN KEY (`almacenCopiadoras_idcopiadoras`)
    REFERENCES `DOM-T`.`almacenCopiadoras` (`idcopiadoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `DOM-T`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_ferreteria1`
    FOREIGN KEY (`ferreteria_idferreteria`)
    REFERENCES `DOM-T`.`ferreteria` (`idferreteria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_electrodomesticos1`
    FOREIGN KEY (`electrodomesticos_idelectrodomesticos`)
    REFERENCES `DOM-T`.`electrodomesticos` (`idelectrodomesticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`categoriaRestautante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`categoriaRestautante` (
  `idcategoriaRestautante` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `restaurate_idrestaurate` INT NOT NULL,
  PRIMARY KEY (`idcategoriaRestautante`),
  INDEX `fk_categoriaRestautante_restaurate1_idx` (`restaurate_idrestaurate` ASC) VISIBLE,
  CONSTRAINT `fk_categoriaRestautante_restaurate1`
    FOREIGN KEY (`restaurate_idrestaurate`)
    REFERENCES `DOM-T`.`restaurate` (`idrestaurate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`almacenCelulares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`almacenCelulares` (
  `idcelulares` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `detalles` TEXT NOT NULL,
  PRIMARY KEY (`idcelulares`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`papeleria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`papeleria` (
  `idpapelerias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `direccion` TEXT NOT NULL,
  PRIMARY KEY (`idpapelerias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`gerente` (
  `idgerente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `restaurate_idrestaurate` INT NOT NULL,
  `almacenRopa_idalmacenRopa` INT NOT NULL,
  `computadoras_idcomputadoras` INT NOT NULL,
  `almacenCelulares_idcelulares` INT NOT NULL,
  `almacenCopiadoras_idcopiadoras` INT NOT NULL,
  `papeleria_idpapelerias` INT NOT NULL,
  `ferreteria_idferreteria` INT NOT NULL,
  `electrodomesticos_idelectrodomesticos` INT NOT NULL,
  PRIMARY KEY (`idgerente`),
  INDEX `fk_gerente_restaurate_idx` (`restaurate_idrestaurate` ASC) VISIBLE,
  INDEX `fk_gerente_almacenRopa1_idx` (`almacenRopa_idalmacenRopa` ASC) VISIBLE,
  INDEX `fk_gerente_computadoras1_idx` (`computadoras_idcomputadoras` ASC) VISIBLE,
  INDEX `fk_gerente_almacenCelulares1_idx` (`almacenCelulares_idcelulares` ASC) VISIBLE,
  INDEX `fk_gerente_almacenCopiadoras1_idx` (`almacenCopiadoras_idcopiadoras` ASC) VISIBLE,
  INDEX `fk_gerente_papeleria1_idx` (`papeleria_idpapelerias` ASC) VISIBLE,
  INDEX `fk_gerente_ferreteria1_idx` (`ferreteria_idferreteria` ASC) VISIBLE,
  INDEX `fk_gerente_electrodomesticos1_idx` (`electrodomesticos_idelectrodomesticos` ASC) VISIBLE,
  CONSTRAINT `fk_gerente_restaurate`
    FOREIGN KEY (`restaurate_idrestaurate`)
    REFERENCES `DOM-T`.`restaurate` (`idrestaurate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerente_almacenRopa1`
    FOREIGN KEY (`almacenRopa_idalmacenRopa`)
    REFERENCES `DOM-T`.`almacenRopa` (`idalmacenRopa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerente_computadoras1`
    FOREIGN KEY (`computadoras_idcomputadoras`)
    REFERENCES `DOM-T`.`almacenComputadoras` (`idcomputadoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerente_almacenCelulares1`
    FOREIGN KEY (`almacenCelulares_idcelulares`)
    REFERENCES `DOM-T`.`almacenCelulares` (`idcelulares`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerente_almacenCopiadoras1`
    FOREIGN KEY (`almacenCopiadoras_idcopiadoras`)
    REFERENCES `DOM-T`.`almacenCopiadoras` (`idcopiadoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerente_papeleria1`
    FOREIGN KEY (`papeleria_idpapelerias`)
    REFERENCES `DOM-T`.`papeleria` (`idpapelerias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerente_ferreteria1`
    FOREIGN KEY (`ferreteria_idferreteria`)
    REFERENCES `DOM-T`.`ferreteria` (`idferreteria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gerente_electrodomesticos1`
    FOREIGN KEY (`electrodomesticos_idelectrodomesticos`)
    REFERENCES `DOM-T`.`electrodomesticos` (`idelectrodomesticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `plato` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `detalles` TEXT NOT NULL,
  `restaurate_idrestaurate` INT NOT NULL,
  PRIMARY KEY (`idmenu`),
  INDEX `fk_menu_restaurate1_idx` (`restaurate_idrestaurate` ASC) VISIBLE,
  CONSTRAINT `fk_menu_restaurate1`
    FOREIGN KEY (`restaurate_idrestaurate`)
    REFERENCES `DOM-T`.`restaurate` (`idrestaurate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `detalles` TEXT NOT NULL,
  `almacenRopa_idalmacenRopa` INT NOT NULL,
  `computadoras_idcomputadoras` INT NOT NULL,
  `almacenCelulares_idcelulares` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `almacenCopiadoras_idcopiadoras` INT NOT NULL,
  `papeleria_idpapelerias` INT NOT NULL,
  `ferreteria_idferreteria` INT NOT NULL,
  `electrodomesticos_idelectrodomesticos` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_almacenRopa1_idx` (`almacenRopa_idalmacenRopa` ASC) VISIBLE,
  INDEX `fk_producto_computadoras1_idx` (`computadoras_idcomputadoras` ASC) VISIBLE,
  INDEX `fk_producto_almacenCelulares1_idx` (`almacenCelulares_idcelulares` ASC) VISIBLE,
  INDEX `fk_producto_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_producto_almacenCopiadoras1_idx` (`almacenCopiadoras_idcopiadoras` ASC) VISIBLE,
  INDEX `fk_producto_papeleria1_idx` (`papeleria_idpapelerias` ASC) VISIBLE,
  INDEX `fk_producto_ferreteria1_idx` (`ferreteria_idferreteria` ASC) VISIBLE,
  INDEX `fk_producto_electrodomesticos1_idx` (`electrodomesticos_idelectrodomesticos` ASC) VISIBLE,
  CONSTRAINT `fk_producto_almacenRopa1`
    FOREIGN KEY (`almacenRopa_idalmacenRopa`)
    REFERENCES `DOM-T`.`almacenRopa` (`idalmacenRopa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_computadoras1`
    FOREIGN KEY (`computadoras_idcomputadoras`)
    REFERENCES `DOM-T`.`almacenComputadoras` (`idcomputadoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_almacenCelulares1`
    FOREIGN KEY (`almacenCelulares_idcelulares`)
    REFERENCES `DOM-T`.`almacenCelulares` (`idcelulares`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `DOM-T`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_almacenCopiadoras1`
    FOREIGN KEY (`almacenCopiadoras_idcopiadoras`)
    REFERENCES `DOM-T`.`almacenCopiadoras` (`idcopiadoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_papeleria1`
    FOREIGN KEY (`papeleria_idpapelerias`)
    REFERENCES `DOM-T`.`papeleria` (`idpapelerias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_ferreteria1`
    FOREIGN KEY (`ferreteria_idferreteria`)
    REFERENCES `DOM-T`.`ferreteria` (`idferreteria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_electrodomesticos1`
    FOREIGN KEY (`electrodomesticos_idelectrodomesticos`)
    REFERENCES `DOM-T`.`electrodomesticos` (`idelectrodomesticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`servicioTecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`servicioTecnico` (
  `idservicioTecnico` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NOT NULL,
  `detalles` TEXT NOT NULL,
  `computadoras_idcomputadoras` INT NOT NULL,
  `almacenCelulares_idcelulares` INT NOT NULL,
  PRIMARY KEY (`idservicioTecnico`),
  INDEX `fk_servicioTecnico_computadoras1_idx` (`computadoras_idcomputadoras` ASC) VISIBLE,
  INDEX `fk_servicioTecnico_almacenCelulares1_idx` (`almacenCelulares_idcelulares` ASC) VISIBLE,
  CONSTRAINT `fk_servicioTecnico_computadoras1`
    FOREIGN KEY (`computadoras_idcomputadoras`)
    REFERENCES `DOM-T`.`almacenComputadoras` (`idcomputadoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicioTecnico_almacenCelulares1`
    FOREIGN KEY (`almacenCelulares_idcelulares`)
    REFERENCES `DOM-T`.`almacenCelulares` (`idcelulares`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `cliente_idcliente` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `menu_idmenu` INT NOT NULL,
  `servicioTecnico_idservicioTecnico` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_pedido_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  INDEX `fk_pedido_menu1_idx` (`menu_idmenu` ASC) VISIBLE,
  INDEX `fk_pedido_servicioTecnico1_idx` (`servicioTecnico_idservicioTecnico` ASC) VISIBLE,
  INDEX `fk_pedido_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `DOM-T`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `DOM-T`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `DOM-T`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_servicioTecnico1`
    FOREIGN KEY (`servicioTecnico_idservicioTecnico`)
    REFERENCES `DOM-T`.`servicioTecnico` (`idservicioTecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `DOM-T`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idmarca`),
  INDEX `fk_marca_producto2_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_marca_producto2`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `DOM-T`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`categoria` (
  `idcategoria` VARCHAR(1) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idcategoria`),
  INDEX `fk_categoria_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `DOM-T`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`talla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`talla` (
  `idtalla` VARCHAR(5) NOT NULL,
  `talla` VARCHAR(20) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idtalla`),
  INDEX `fk_talla_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_talla_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `DOM-T`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`modelo` (
  `idmodelo` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idmodelo`),
  INDEX `fk_modelo_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `DOM-T`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`serie` (
  `idserie` INT NOT NULL AUTO_INCREMENT,
  `serie` VARCHAR(45) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idserie`),
  INDEX `fk_serie_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_serie_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `DOM-T`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idmarca`),
  INDEX `fk_marca_producto2_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_marca_producto2`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `DOM-T`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOM-T`.`logo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOM-T`.`logo` (
  `idlogo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `logo` MEDIUMBLOB NOT NULL,
  `almacenComputadoras_idcomputadoras` INT NOT NULL,
  `almacenCelulares_idcelulares` INT NOT NULL,
  `almacenCopiadoras_idcopiadoras` INT NOT NULL,
  `papeleria_idpapelerias` INT NOT NULL,
  `ferreteria_idferreteria` INT NOT NULL,
  `restaurate_idrestaurate` INT NOT NULL,
  `almacenRopa_idalmacenRopa` INT NOT NULL,
  `electrodomesticos_idelectrodomesticos` INT NOT NULL,
  PRIMARY KEY (`idlogo`),
  INDEX `fk_logo_almacenComputadoras1_idx` (`almacenComputadoras_idcomputadoras` ASC) VISIBLE,
  INDEX `fk_logo_almacenCelulares1_idx` (`almacenCelulares_idcelulares` ASC) VISIBLE,
  INDEX `fk_logo_almacenCopiadoras1_idx` (`almacenCopiadoras_idcopiadoras` ASC) VISIBLE,
  INDEX `fk_logo_papeleria1_idx` (`papeleria_idpapelerias` ASC) VISIBLE,
  INDEX `fk_logo_ferreteria1_idx` (`ferreteria_idferreteria` ASC) VISIBLE,
  INDEX `fk_logo_restaurate1_idx` (`restaurate_idrestaurate` ASC) VISIBLE,
  INDEX `fk_logo_almacenRopa1_idx` (`almacenRopa_idalmacenRopa` ASC) VISIBLE,
  INDEX `fk_logo_electrodomesticos1_idx` (`electrodomesticos_idelectrodomesticos` ASC) VISIBLE,
  CONSTRAINT `fk_logo_almacenComputadoras1`
    FOREIGN KEY (`almacenComputadoras_idcomputadoras`)
    REFERENCES `DOM-T`.`almacenComputadoras` (`idcomputadoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logo_almacenCelulares1`
    FOREIGN KEY (`almacenCelulares_idcelulares`)
    REFERENCES `DOM-T`.`almacenCelulares` (`idcelulares`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logo_almacenCopiadoras1`
    FOREIGN KEY (`almacenCopiadoras_idcopiadoras`)
    REFERENCES `DOM-T`.`almacenCopiadoras` (`idcopiadoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logo_papeleria1`
    FOREIGN KEY (`papeleria_idpapelerias`)
    REFERENCES `DOM-T`.`papeleria` (`idpapelerias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logo_ferreteria1`
    FOREIGN KEY (`ferreteria_idferreteria`)
    REFERENCES `DOM-T`.`ferreteria` (`idferreteria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logo_restaurate1`
    FOREIGN KEY (`restaurate_idrestaurate`)
    REFERENCES `DOM-T`.`restaurate` (`idrestaurate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logo_almacenRopa1`
    FOREIGN KEY (`almacenRopa_idalmacenRopa`)
    REFERENCES `DOM-T`.`almacenRopa` (`idalmacenRopa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logo_electrodomesticos1`
    FOREIGN KEY (`electrodomesticos_idelectrodomesticos`)
    REFERENCES `DOM-T`.`electrodomesticos` (`idelectrodomesticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
